; Sprite mappings - generated by Flex - Sonic 1 format

Map_Lamp:
	dc.w AMQ_Frame0-Map_Lamp, YDG_Frame1-Map_Lamp
	dc.w NLW_Frame2-Map_Lamp, BQZ_Frame3-Map_Lamp


AMQ_Frame0: dc.b  $6
	dc.b  $E4, $1, $0, $0, $F8
	dc.b  $E4, $1, $8, $0, $0
	dc.b  $F4, $3, $0, $2, $F8
	dc.b  $F4, $3, $8, $2, $0
	dc.b  $D4, $1, $0, $6, $F8
	dc.b  $D4, $1, $8, $6, $0
YDG_Frame1: dc.b  $4
	dc.b  $E4, $1, $0, $0, $F8
	dc.b  $E4, $1, $8, $0, $0
	dc.b  $F4, $3, $0, $2, $F8
	dc.b  $F4, $3, $8, $2, $0
NLW_Frame2: dc.b  $2
	dc.b  $F8, $1, $0, $8, $F8
	dc.b  $F8, $1, $8, $8, $0
BQZ_Frame3: dc.b  $6
	dc.b  $E4, $1, $0, $0, $F8
	dc.b  $E4, $1, $8, $0, $0
	dc.b  $F4, $3, $0, $2, $F8
	dc.b  $F4, $3, $8, $2, $0
	dc.b  $D4, $1, $0, $8, $F8
	dc.b  $D4, $1, $8, $8, $0
