; Sprite mappings - generated by Flex - Sonic 1 format

Map_Moto:
	dc.w WTD_Frame0-Map_Moto, XMZ_Frame1-Map_Moto
	dc.w WYB_Frame2-Map_Moto, ZJV_Frame3-Map_Moto
	dc.w CMF_Frame4-Map_Moto

WTD_Frame0: dc.b  $3
	dc.b  $E8, $C, $0, $0, $E8
	dc.b  $F0, $D, $0, $7, $E8
	dc.b  $0, $D, $0, $F, $E8
XMZ_Frame1: dc.b  $1
	dc.b  $FA, $0, $0, $4, $10
WYB_Frame2: dc.b  $1
	dc.b  $FA, $0, $0, $5, $10
ZJV_Frame3: dc.b  $1
	dc.b  $FA, $0, $0, $6, $10
CMF_Frame4: dc.b  $0
